CIRCUITPY_WIFI_SSID = "WIFI SSID"
CIRCUITPY_WIFI_PASSWORD = "WIFI PSK"
MQTT_HOST = "MQTT BROKER HOSTNAME OR IP ADDRESS"
MQTT_PORT = 1883
MQTT_USERNAME = "MQTT BROKER USERNAME"
MQTT_PASSWORD = "MQTT BROKER PASSWORD"
MQTT_SENSOR_TOPIC = "MQTT TOPIC FOR SENSOR READINGS"
MQTT_UPDATE_FREQ_TOPIC = "MQTT TOPIC THAT ADJUSTS UPDATE FREQUENCY"